const adminRoutes = {
    sign_in: "/sign_in",
    logout: "/sign_out",
    refresh_token: "/refresh_token",
    users: "/users",
    providers: "/providers",
    get_services: "/services",
    user_block: "/block_user",
    user_unblock: "/unblock_user",
    provider_block: "/block_provider",
    provider_unblock: "/unblock_provider",
    approvals: "/approvals",
    approval_details: "/approval_details",
    approval_update: "/approval_update",
    manage_service: "/manage_service",
    add_service: "/add_service",
    update_service: "/update_service",
    bookings: "bookings",
};
export default adminRoutes;
