const providerRoutes = {
    sign_in: "/sign_in",
    sign_up: "/sign_up",
    otp_verify: "/otp_verify",
    otp_resend: "/otp_resend",
    logout: "/sign_out",
    refresh_token: "/refresh_token",
    get_services: "/services",
    o_auth: "/o_auth",
    update_profile: "update_profile",
    get_profile_details: "/profile",
    register: "/register",
    forgot_password: "/forgot_password",
    confirm_password: "/confirm_password",
    forgot_otp_verify: "/forgot_otp_verify",
    reset_password: "/reset_password",
    schedule: "/schedule",
    booking_request: "/booking_requests",
    bookings: "bookings",
    booking_details: "/booking_details",
    payments: "/payments",
    chats: "/chats",
    dashboard: "/dashboard",
    monthly_revenue: "/revenue",
};
export default providerRoutes;
