const userRoutes = {
    sign_in: "/sign_in",
    sign_up: "/sign_up",
    otp_verify: "/otp_verify",
    forgot_otp_verify: "/forgot_otp_verify",
    otp_resend: "/otp_resend",
    logout: "/sign_out",
    refresh_token: "/refresh_token",
    o_auth: `/o_auth`,
    update_profile: "/update_profile",
    get_details: "/",
    forgot_password: "/forgot_password",
    confirm_password: "/confirm_password",
    reset_password: "/reset_password",
    add_address: "/add_address",
    get_addresses: "/addresses",
    get_address: "/address",
    edit_address: "/edit_address",
    delete_address: "/addresses",
    slots: "slots",
};
export default userRoutes;
